### ISSUE TITLE
powerstack.org - No longer hosted

### ISSUE THREAD

**Issue by jaredledvina** [arioch/puppet-redis#103]
powerstack.org appears to be taken down. Are there other providers for the RPM's for REHL based distros?

**Comment by petems** [comment]
redis is avaliable in EPEL for RHEL/CentOS 7+

For RHEL/Centos 6, looks like we can shift to http://rpms.famillecollet.com/enterprise/6/remi/x86_64/redis-3.2.4-1.el6.remi.x86_64.rpm

```
[remi]
name=Les RPM de remi pour Enterprise Linux 6 - $basearch
#baseurl=http://rpms.famillecollet.com/enterprise/6/remi/$basearch/
mirrorlist=http://rpms.famillecollet.com/enterprise/6/remi/mirror
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-remi
```

**Comment by petems** [comment]
Actually, even easier, EPEL has redis for RHEL 5,6 and 7 now 👍

**Comment by v6** [comment]
// , Do you have any guidelines for how to set this up so that it may also use an internally hosted repository? 

E.g. repository.bigcorp.com? 

Also, it looks like EPEL only allows ReDiS 2 for CEntOS 6: 

<img width="346" alt="image" src="https://cloud.githubusercontent.com/assets/5750764/22228536/b7e9a1c6-e186-11e6-8901-d289dc27b975.png">
