### ISSUE TITLE
Use puppetlabs-inifile instead of relying on exec

### ISSUE THREAD

**Issue by johanfleury** [arioch/puppet-redis#151]
Hi.

While reading the module's code, I was wondering why you don't use [puppetlabs-inifile](https://forge.puppet.com/puppetlabs/inifile) instead of relying on [`exec { "cp -p" }`](https://github.com/arioch/puppet-redis/blob/master/manifests/config.pp#L107)?

You could call `ini_settings` (or `create_ini_settings`) with `section => undef` and `key_val_separator => ' '`.

What do you think?

**Comment by petems** [comment]
So, the original reason that the exec is used is because managing the file as a whole is a lot easier than having multiple resources for each config setting.

The exec that copies the file is because redis manages it's own config, so sometimes changes entries within the config. So having it create and copy it over means that the redis edited entries don't get overwritten immediately.

**Comment by petems** [comment]
Closing as sticking with the template approach
