### ISSUE TITLE
The fix for issue #192 broke service_managed false

### ISSUE THREAD

**Issue by mbaldessari** [arioch/puppet-redis#197]
I have the following hiera values:
redis::managed_by_cluster_manager": true
redis::service_manage": false
redis::notify_service": false

But now an 'include ::redis' gives me:
Error: Could not find dependent Service[redis] for Augeas[Systemd redis ulimit] at /etc/puppet/modules/redis/manifests/ulimit.pp:44

Did you mean to make https://github.com/arioch/puppet-redis/blob/master/manifests/ulimit.pp#L31 an 'elsif' and not an 'if'?

**Comment by petems** [comment]
Good point, I should probably only refresh the service if it's being managed by Puppet. 

In fact, since this is in the config class, it should automatically notify the service if it's enabled anyway.

I'll open a PR and also add an acceptance test with this setting to make sure this doesn't regress 😄

**Comment by mbaldessari** [comment]
Perfect, thanks :)
