### ISSUE TITLE
Ulimit configuration broken for systemd

### ISSUE THREAD

**Issue by jarro2783** [arioch/puppet-redis#268]
It appears that the `ulimit` implementation for systemd has never worked. I just get an empty file. This is particularly a problem on Ubuntu 18, where systemd reports a unit as masked if it has an empty drop-in file.

I can work around it by setting `redis::ulimit => false`, because that then doesn't instantiate the `redis::ulimit` class at all.

**Comment by cmseal** [comment]
I've just come across the same issue, re: 18.04 and the unit being masked, thus unable to 'enable' the service.

**Comment by bahner** [comment]
It seems that the problem is that limit.conf is empty. That is, eeeeh "interpreted" by systemd as if it's -> /dev/null'ed. It would say this is a bug in systemd , but maybe it's by design. I don't know. The solution here seems to be: don't touch or define limit.conf unless there's a reason too.
I will see if I can come up with a PR for this.

**Comment by arioch** [comment]
Should be fixed by merging @bahner's PR.
Thanks again.
