### ISSUE TITLE
Error on CentOS 7 when manage_repo: true

### ISSUE THREAD

**Issue by claflico** [arioch/puppet-redis#44]
On new minimal install of CentOS 7 I'm getting the following error during puppet runs:

Error: Failed to apply catalog: Parameter baseurl failed on Yumrepo[powerstack]: Validate method failed for class baseurl: bad URI(is not URI?): Fail[Operating at /etc/puppet/environments/development/modules/common/redis/manifests/preinstall.pp:28

puppet-3.8.1-1.el7.noarch

Thanks

**Comment by eoly** [comment]
The problem is on preinstall.pp:13
https://github.com/arioch/puppet-redis/blob/master/manifests/preinstall.pp#L13

```
class redis::preinstall {
  if $::redis::manage_repo {
    case $::operatingsystem {
      'RedHat', 'CentOS', 'Scientific', 'OEL': {
        $rpm_url = $::operatingsystemrelease ? {
          /^5/    => "http://download.powerstack.org/5/${::architecture}/",
          /^6/    => "http://download.powerstack.org/6/${::architecture}/",
          default => Fail['Operating system or release version not supported.'],
        }
```

RHEL 7 is not supported. Instead of failing with a parse error $rpm_url is getting assigned the value "Fail['Operating system or release version not supported.']". You cannot call the fail function in a Selector expression.

As a work around until this gets fixed. Install the epel repos. Then declare the redis class with manage_repo => false, or just leave out the manage_repo parameter all together since it is false by default.

**Comment by arioch** [comment]
The ```redis::preinstall``` should only be used development setups.
Just ```yum install epel-release``` should get you up and running though if you're not managing your repos using a module.

**Comment by arioch** [comment]
I've just added 312e002600e8b672543bee60c21e0173a072d3a5 to help you with that.

**Comment by claflico** [comment]
awesome, thanks.
