### ISSUE TITLE
Unable to bring in as a dependency

### ISSUE THREAD

**Issue by davpx** [arioch/puppet-redis#47]
I've tried adding this to my Modulefile, also tried calling it in my Puppetfile but librarian-puppet always returns "Cannot resolve the dependencies". Is there a problem with this module on the forge?

**Comment by arioch** [comment]
Could have been a temporary glitch as it seems to work just fine on my box...

```
$ puppet module install arioch-redis
Notice: Preparing to install into /Users/tom/.puppetlabs/etc/code/modules ...
Notice: Created target directory /Users/tom/.puppetlabs/etc/code/modules
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/Users/tom/.puppetlabs/etc/code/modules
└─┬ arioch-redis (v1.1.1)
  └─┬ puppetlabs-apt (v2.1.1)
    └── puppetlabs-stdlib (v4.7.0)
```

**Comment by arioch** [comment]
I've cut a new release after posting my first reply. Works fine too...

**Comment by gblair** [comment]
I've run into this issue, as well. It occurs when `puppetlabs-apt` is used alongside `arioch-redis`, because the two specify allowed version sets for `puppetlabs-stdlib` that do not intersect.

`puppetlabs-apt`: `>= 4.5.0 < 5.0.0` (https://github.com/puppetlabs/puppetlabs-apt/blob/f05e43c28588a280a42333f9ca3a506a7121849d/metadata.json#L11)
`arioch-redis`: `>= 1.0.2 <3.0.0` (https://github.com/arioch/puppet-redis/blob/master/metadata.json#L12)
